// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using StudentAdmissionAppApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace StudentAdmissionAppApi.Models
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<SP_StudentAdmissionResult>> SP_StudentAdmissionAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);

        List<SP_StudentAdmissionResult> SP_StudentAdmission(OutputParameter<int> returnValue = null);
    }
}
