// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentAdmissionAppApi.Models
{
    public partial class SP_StudentAdmissionResult
    {
        public string stagename { get; set; }
        public string standardname { get; set; }
        public int? totalstudent { get; set; }
    }
}
