// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentAdmissionAppApi.Models
{
    public partial class Stages
    {
        public Stages()
        {
            Standards = new HashSet<Standards>();
            Students = new HashSet<Students>();
        }

        public int StageId { get; set; }
        public string StageName { get; set; }
        public string StageDescription { get; set; }

        public virtual ICollection<Standards> Standards { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}