// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentAdmissionAppApi.Models
{
    public partial class Standards
    {
        public Standards()
        {
            Students = new HashSet<Students>();
        }

        public int StandardId { get; set; }
        public string StandardName { get; set; }
        public string ClassTeacherName { get; set; }
        public int StageId { get; set; }

        public virtual Stages Stage { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}